#
# Copyright 2023 Oracle and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[versions]
micronaut-platform = "4.3.7"
micronaut-micrometer = "5.4.0-oracle-00001"
micronaut-tracing = "6.4.1-oracle-00001"
micronaut-serialization = "2.8.2-oracle-00001"
micronaut-kafka = "5.3.0-oracle-00001"
micronaut-flyway = "7.1.0-oracle-00001"
micronaut-discovery = "4.2.0-oracle-00001"
micronaut-oraclecloud = "3.7.2-oracle-00001"
micronaut-openapi = "6.6.3-oracle-00001"
micronaut-cache = "4.2.2-oracle-00001"
micronaut-mongo = "5.2.0-oracle-00001"
micronaut-security = "4.6.10-oracle-00001"
micronaut-data = "4.6.0-oracle-00001"
micronaut-liquibase = "6.2.0-oracle-00001"
micronaut-object-storage = "2.3.0-oracle-00001"
micronaut-email = "2.4.0-oracle-00001"
micronaut-sql = "5.5.1-oracle-00001"
micronaut-core = "4.3.13-oracle-00001"
micronaut-reactor = "3.2.1-oracle-00001"
micronaut-jaxrs = "4.3.0-oracle-00001"
micronaut-picocli = "5.2.0-oracle-00001"
micronaut-kubernetes = "6.0.0-oracle-00001"
micronaut-validation = "4.4.4-oracle-00001"
micronaut-views = "5.1.0-oracle-00001"
micronaut-gradle-plugin = "4.3.6"
apache-commons-compress = "1.26.1"
bouncycastle = "1.77"
kotlin = "1.8.22"
logback = "1.5.3"
guava = "32.1.3-jre"
opentelemetry-semconv = "1.30.1-alpha"
google-cloud-logging = "0.131.4-alpha"
aws-msk-iam-auth = "2.0.3"
micronaut-session = "4.2.0-oracle-00001"
micronaut-maven-plugin = "4.5.2"
micronaut-maven-test-resources-plugin = "2.4.0"
test-containers-oracle-xe = "1.19.7"
spring-boot-gradle-plugin = "3.2.4"
io-spring-gradle-dependency-management-plugin = "1.1.4"
org-springframework-boot-spring-boot-starter-parent = "3.2.4"
okhttp = "4.12.0"
gax-grpc = "2.41.0"
gax = "2.41.0"

[libraries]
io-micronaut-discovery-micronaut-discovery-client = { module = 'io.micronaut.discovery:micronaut-discovery-client', version.ref = 'micronaut-discovery'}
io-micronaut-openapi-micronaut-openapi = { module = 'io.micronaut.openapi:micronaut-openapi', version.ref = 'micronaut-openapi'}
io-micronaut-sql-micronaut-jdbc = { module = 'io.micronaut.sql:micronaut-jdbc', version.ref = 'micronaut-sql'}
io-micronaut-sql-micronaut-jdbc-tomcat = { module = 'io.micronaut.sql:micronaut-jdbc-tomcat', version.ref = 'micronaut-sql'}
io-micronaut-micronaut-aop = { module = 'io.micronaut:micronaut-aop', version.ref = 'micronaut-core'}
io-micronaut-micronaut-buffer-netty = { module = 'io.micronaut:micronaut-buffer-netty', version.ref = 'micronaut-core'}
io-micronaut-micronaut-context = { module = 'io.micronaut:micronaut-context', version.ref = 'micronaut-core'}
io-micronaut-micronaut-context-propagation = { module = 'io.micronaut:micronaut-context-propagation', version.ref = 'micronaut-core'}
io-micronaut-micronaut-core = { module = 'io.micronaut:micronaut-core', version.ref = 'micronaut-core'}
io-micronaut-micronaut-core-reactive = { module = 'io.micronaut:micronaut-core-reactive', version.ref = 'micronaut-core'}
io-micronaut-micronaut-discovery-core = { module = 'io.micronaut:micronaut-discovery-core', version.ref = 'micronaut-core'}
io-micronaut-micronaut-function = { module = 'io.micronaut:micronaut-function', version.ref = 'micronaut-core'}
io-micronaut-micronaut-function-client = { module = 'io.micronaut:micronaut-function-client', version.ref = 'micronaut-core'}
io-micronaut-micronaut-function-web = { module = 'io.micronaut:micronaut-function-web', version.ref = 'micronaut-core'}
io-micronaut-micronaut-graal = { module = 'io.micronaut:micronaut-graal', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http = { module = 'io.micronaut:micronaut-http', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-client = { module = 'io.micronaut:micronaut-http-client', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-client-core = { module = 'io.micronaut:micronaut-http-client-core', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-netty = { module = 'io.micronaut:micronaut-http-netty', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-server = { module = 'io.micronaut:micronaut-http-server', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-server-netty = { module = 'io.micronaut:micronaut-http-server-netty', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-server-tck = { module = 'io.micronaut:micronaut-http-server-tck', version.ref = 'micronaut-core'}
io-micronaut-micronaut-http-validation = { module = 'io.micronaut:micronaut-http-validation', version.ref = 'micronaut-core'}
io-micronaut-micronaut-inject = { module = 'io.micronaut:micronaut-inject', version.ref = 'micronaut-core'}
io-micronaut-micronaut-inject-groovy = { module = 'io.micronaut:micronaut-inject-groovy', version.ref = 'micronaut-core'}
io-micronaut-micronaut-inject-java = { module = 'io.micronaut:micronaut-inject-java', version.ref = 'micronaut-core'}
io-micronaut-micronaut-inject-kotlin-test = { module = 'io.micronaut:micronaut-inject-kotlin-test', version.ref = 'micronaut-core'}
io-micronaut-micronaut-jackson-core = { module = 'io.micronaut:micronaut-jackson-core', version.ref = 'micronaut-core'}
io-micronaut-micronaut-jackson-databind = { module = 'io.micronaut:micronaut-jackson-databind', version.ref = 'micronaut-core'}
io-micronaut-micronaut-json-core = { module = 'io.micronaut:micronaut-json-core', version.ref = 'micronaut-core'}
io-micronaut-micronaut-management = { module = 'io.micronaut:micronaut-management', version.ref = 'micronaut-core'}
io-micronaut-micronaut-messaging = { module = 'io.micronaut:micronaut-messaging', version.ref = 'micronaut-core'}
io-micronaut-micronaut-core-bom = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut-core'}
io-micronaut-micronaut-router = { module = 'io.micronaut:micronaut-router', version.ref = 'micronaut-core'}
io-micronaut-micronaut-runtime = { module = 'io.micronaut:micronaut-runtime', version.ref = 'micronaut-core'}
io-micronaut-micronaut-session = { module = 'io.micronaut.session:micronaut-session', version.ref = 'micronaut-session'}
io-micronaut-micronaut-websocket = { module = 'io.micronaut:micronaut-websocket', version.ref = 'micronaut-core'}
io-micronaut-cache-micronaut-cache-core = { module = 'io.micronaut.cache:micronaut-cache-core', version.ref = 'micronaut-cache'}
io-micronaut-data-micronaut-data-bom = { module = 'io.micronaut.data:micronaut-data-bom', version.ref = 'micronaut-data'}
io-micronaut-email-micronaut-email-javamail = { module = 'io.micronaut.email:micronaut-email-javamail', version.ref = 'micronaut-email'}
io-micronaut-email-micronaut-email-javamail-composer = { module = 'io.micronaut.email:micronaut-email-javamail-composer', version.ref = 'micronaut-email'}
io-micronaut-flyway-micronaut-flyway-bom = { module = 'io.micronaut.flyway:micronaut-flyway-bom', version.ref = 'micronaut-flyway'}
io-micronaut-jaxrs-micronaut-jaxrs-bom = { module = 'io.micronaut.jaxrs:micronaut-jaxrs-bom', version.ref = 'micronaut-jaxrs'}
io-micronaut-kafka-micronaut-kafka = { module = 'io.micronaut.kafka:micronaut-kafka', version.ref = 'micronaut-kafka'}
io-micronaut-kubernetes-micronaut-kubernetes-bom = { module = 'io.micronaut.kubernetes:micronaut-kubernetes-bom', version.ref = 'micronaut-kubernetes'}
io-micronaut-liquibase-micronaut-liquibase-bom = { module = 'io.micronaut.liquibase:micronaut-liquibase-bom', version.ref = 'micronaut-liquibase'}
io-micronaut-micrometer-micronaut-micrometer-core = { module = 'io.micronaut.micrometer:micronaut-micrometer-core', version.ref = 'micronaut-micrometer'}
io-micronaut-micrometer-micronaut-micrometer-registry-cloudwatch = { module = 'io.micronaut.micrometer:micronaut-micrometer-registry-cloudwatch', version.ref = 'micronaut-micrometer'}
io-micronaut-micrometer-micronaut-micrometer-registry-stackdriver = { module = 'io.micronaut.micrometer:micronaut-micrometer-registry-stackdriver', version.ref = 'micronaut-micrometer'}
io-micronaut-mongodb-micronaut-mongo-bom = { module = 'io.micronaut.mongodb:micronaut-mongo-bom', version.ref = 'micronaut-mongo'}
io-micronaut-objectstorage-micronaut-object-storage-aws = { module = 'io.micronaut.objectstorage:micronaut-object-storage-aws', version.ref = 'micronaut-object-storage'}
io-micronaut-objectstorage-micronaut-object-storage-core = { module = 'io.micronaut.objectstorage:micronaut-object-storage-core', version.ref = 'micronaut-object-storage'}
io-micronaut-objectstorage-micronaut-object-storage-oracle-cloud = { module = 'io.micronaut.objectstorage:micronaut-object-storage-oracle-cloud', version.ref = 'micronaut-object-storage'}
io-micronaut-objectstorage-micronaut-object-storage-gcp = { module = 'io.micronaut.objectstorage:micronaut-object-storage-gcp', version.ref = 'micronaut-object-storage'}
io-micronaut-openapi-micronaut-openapi-bom = { module = 'io.micronaut.openapi:micronaut-openapi-bom', version.ref = 'micronaut-openapi'}
io-micronaut-picocli-micronaut-picocli-bom = { module = 'io.micronaut.picocli:micronaut-picocli-bom', version.ref = 'micronaut-picocli'}
io-micronaut-reactor-micronaut-reactor-bom = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = 'micronaut-reactor'}
io-micronaut-security-micronaut-security-bom = { module = 'io.micronaut.security:micronaut-security-bom', version.ref = 'micronaut-security'}
io-micronaut-serde-micronaut-serde-bom = { module = 'io.micronaut.serde:micronaut-serde-bom', version.ref = 'micronaut-serialization'}
io-micronaut-sql-micronaut-sql-bom = { module = 'io.micronaut.sql:micronaut-sql-bom', version.ref = 'micronaut-sql'}
io-micronaut-tracing-micronaut-tracing-bom = { module = 'io.micronaut.tracing:micronaut-tracing-bom', version.ref = 'micronaut-tracing'}
io-micronaut-validation-micronaut-validation-bom = { module = 'io.micronaut.validation:micronaut-validation-bom', version.ref = 'micronaut-validation'}
io-micronaut-oraclecloud-micronaut-oraclecloud-bom = { module = 'io.micronaut.oraclecloud:micronaut-oraclecloud-bom', version.ref = 'micronaut-oraclecloud'}
io-micronaut-views-micronaut-views-core = { module = 'io.micronaut.views:micronaut-views-core', version.ref = 'micronaut-views'}
io-micronaut-views-micronaut-views-jte = { module = 'io.micronaut.views:micronaut-views-jte', version.ref = 'micronaut-views'}
org-apache-commons-commons-compress = { module = 'org.apache.commons:commons-compress', version.ref = 'apache-commons-compress'}
org-bouncycastle-bcprov-jdk18on = { module = 'org.bouncycastle:bcprov-jdk18on', version.ref = 'bouncycastle'}
org-bouncycastle-bcpkix-jdk18on = { module = 'org.bouncycastle:bcpkix-jdk18on', version.ref = 'bouncycastle'}
org-jetbrains-kotlin-kotlin-annotation-processing-embeddable = { module = 'org.jetbrains.kotlin:kotlin-annotation-processing-embeddable', version.ref = 'kotlin'}
org-jetbrains-kotlin-kotlin-compiler-embeddable = { module = 'org.jetbrains.kotlin:kotlin-compiler-embeddable', version.ref = 'kotlin'}
org-jetbrains-kotlin-kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = 'kotlin'}
org-jetbrains-kotlin-kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib', version.ref = 'kotlin'}
org-jetbrains-kotlin-kotlin-stdlib-jdk8 = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin'}
org-jetbrains-kotlin-kotlin-test = { module = 'org.jetbrains.kotlin:kotlin-test', version.ref = 'kotlin'}
ch-qos-logback-logback-classic = { module = 'ch.qos.logback:logback-classic', version.ref = 'logback'}
ch-qos-logback-logback-core = { module = 'ch.qos.logback:logback-core', version.ref = 'logback'}
com-google-guava-guava = { module = 'com.google.guava:guava', version.ref = 'guava'}
io-opentelemetry-opentelemetry-semconv = { module = 'io.opentelemetry:opentelemetry-semconv', version.ref = 'opentelemetry-semconv'}
com-google-cloud-google-cloud-logging-logback = { module = 'com.google.cloud:google-cloud-logging-logback', version.ref = 'google-cloud-logging'}
software-amazon-msk-aws-msk-iam-auth = { module = 'software.amazon.msk:aws-msk-iam-auth', version.ref = 'aws-msk-iam-auth'}
com-squareup-okhttp3-okhttp = { module = 'com.squareup.okhttp3:okhttp', version.ref = 'okhttp'}
com-squareup-okhttp3-logging-interceptor = { module = 'com.squareup.okhttp3:logging-interceptor', version.ref = 'okhttp'}
com-google-api-gax-grpc = { module = 'com.google.api:gax-grpc', version.ref = 'gax-grpc'}
com-google-api-gax = { module = 'com.google.api:gax', version.ref = 'gax'}

# plugins that will be exluded from bom file (exclude-) prefix means don't add it into gcn-bom
exclude-micronaut-crac-plugin = { module = "io.micronaut.gradle:micronaut-crac-plugin", version.ref = "micronaut-gradle-plugin" }
exclude-micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
exclude-micronaut-test-resources-plugin = { module = "io.micronaut.gradle:micronaut-test-resources-plugin", version.ref = "micronaut-gradle-plugin" }
exclude-io-micronaut-platform-micronaut-parent = { module = 'io.micronaut.platform:micronaut-parent', version.ref = 'micronaut-platform'}
exclude-io-micronaut-maven-plugin = { module = 'io.micronaut.maven:micronaut-maven-plugin', version.ref = 'micronaut-maven-plugin'}
exclude-io-micronaut-maven-test-resources-plugin = { module = 'io.micronaut.testresources:micronaut-test-resources-core', version.ref = 'micronaut-maven-test-resources-plugin'}
exclude-org-testcontainers-oracle-xe = { module = 'org.testcontainers:oracle-xe', version.ref = 'test-containers-oracle-xe'}
exclude-org-springframework-boot = { module = 'org.springframework.boot:spring-boot-gradle-plugin', version.ref = 'spring-boot-gradle-plugin'}
exclude-io-spring-gradle-dependency-management-plugin = { module = 'io.spring.gradle:dependency-management-plugin', version.ref = 'io-spring-gradle-dependency-management-plugin'}
exclude-org-springframework-boot-spring-boot-starter-parent = { module = "org.springframework.boot:spring-boot-starter-parent", version.ref = "org-springframework-boot-spring-boot-starter-parent"}
